
@startuml
participant 注册页面 as register

participant 登录页面 as login

participant 企业微信首页 as main

participant 通讯录页面 as contact

participant 添加成员页面 as add_member

participant 添加部门 as add_department

participant 导入通讯录 as import_address_book


login -> register: 进行注册
login -> login: 扫码登录

main -> contact: 点击通讯录按钮
main -> add_member: 点击添加成员按钮
main -> import_address_book: 点击导入通讯录


contact -> add_member: 添加成员操作
contact -> add_department: 添加部门操作
contact -> contact: 获取成员列表
contact -> contact: 获取部门列表

add_member -> contact : 1. 填写人员信息 \n2.点击保存

add_department -> contact: 1. 填写部门信息 \n2. 点击确定


@enduml


